#!/usr/bin/env ruby

require 'benchmark'

require 'enginevib/launcher'
require 'enginevib/io'
require 'enginevib/main'
require 'enginevib/sensor'
require 'enginevib/output'
require 'enginevib/system'
require 'enginevib/soft_ticker'
require 'enginevib/scheduler'
require 'enginevib/controller'
require 'enginevib/stats'
require 'enginevib/averager'


require 'rtos'

Enginevib::Main.new.launch
